public class Second{
	public static void main(String[]arg){
		byte noOfStudents = 100;
		byte noOfTeachers = 50;
		byte noOfFamilyMembers = 5;
		byte noOfInstituteInBangalore = 75;
		byte noOfAlphabet = 26;
		byte noOfChildrensInGarden = 30;
		byte noOfMonthsInAYear = 12;
		byte noOfWorksInAnOffice = 121;
		byte noOfPensIHave = 3;
		byte noOfTheethsInHumanBody = 32;
		short parksInBanglore = 2000;
		short costOfInstitute = 20000;
		short populationInBtm = 10000;
		short pagesInADictionary = 600;
		short noOfAnimalsInAZoo = 4000;
		short noOfCountrysInTheWorld = 195;
		short noOfMobileCompanysInWorld = 200;
		short templesInBanglore = 1000;
		short noOfCharectorsInTweet = 280;
		short noOfBonesInHumanBody = 208;
		int noOfPopulationOfNewyorkCity = 214783222;
		int distanceBetweenTwoCities = 13498745;
		int noOfBooksInALargeLibrary = 64323;
		int priceOfLuxuryCar = 1453692;
		int valueOfLargeRealEstateProperty = 1456784;
		int noOfStudentsInLargeUniversity = 60000;
		int employsInALargeCorporation = 70000;
		int subscribersToAYouTubeChannel = 83456;
		int budgetOfTheMovie = 142356786;
		int noOfPeopleAttendingMajorSportsEvent = 50000;
		long noOfTreesInTheWorld = 4536785443L;
		long noOfCarInTheWorld = 5432187656L;
		long noOfPopulationInWorld = 4567458984L;
		long noOfStarsInTheMilkyWayGalaxy = 3145678987L;
		long ageOfEarth = 4500000000L;
		long ageOfSun = 4600000000L;
		long noOfCellsInHumanBody = 5164567456L;
		long mobileNo = 9856743689L;
		long noOfAtomsInADropOfWater = 3147483647L;
		long noOfRiversInTheWorld = 9223372036L;
		System.out.println(noOfFamilyMembers);
		System.out.println(noOfInstituteInBangalore);
		System.out.println(noOfAlphabet);
		System.out.println(noOfChildrensInGarden);
		System.out.println(noOfMonthsInAYear);
		System.out.println(noOfWorksInAnOffice);
		System.out.println(noOfPensIHave);
		System.out.println(noOfTheethsInHumanBody);
		System.out.println(parksInBanglore);
		System.out.println(costOfInstitute);
		System.out.println(populationInBtm);
		System.out.println(pagesInADictionary);
		System.out.println(noOfAnimalsInAZoo);
		System.out.println(noOfCountrysInTheWorld);
		System.out.println(noOfMobileCompanysInWorld);
		System.out.println(templesInBanglore);
		System.out.println(noOfCharectorsInTweet);
		System.out.println(noOfBonesInHumanBody);
		System.out.println(noOfPopulationOfNewyorkCity);
		System.out.println(distanceBetweenTwoCities);
		System.out.println(noOfBooksInALargeLibrary);
		System.out.println(priceOfLuxuryCar);
		System.out.println(valueOfLargeRealEstateProperty);
		System.out.println(noOfStudentsInLargeUniversity);
		System.out.println(employsInALargeCorporation);
		System.out.println(subscribersToAYouTubeChannel);
		System.out.println(budgetOfTheMovie);
		System.out.println(noOfPeopleAttendingMajorSportsEvent);
		System.out.println(noOfTreesInTheWorld);
		System.out.println(noOfCarInTheWorld);
		System.out.println(noOfPopulationInWorld);
		System.out.println(noOfStarsInTheMilkyWayGalaxy);
		System.out.println(ageOfEarth);
		System.out.println(ageOfSun);
		System.out.println(noOfCellsInHumanBody);
		System.out.println(mobileNo);
		System.out.println(noOfAtomsInADropOfWater);
		System.out.println(noOfRiversInTheWorld);
		        }
}